### ISSUE TITLE
When do new versions get released

### ISSUE THREAD

**Issue by CodeCubeNeo** [NeoApplications/Neo-Store#209]
Hello! I was wondering when will the app get updated in the fdroid. Also is there any other way to get semi-development builds, since some of us dont have telegram. If not would you maybe add a dev release every month (or maybe week?) under github releases, so that we can try and use the new features. I think it would be really helpful to have the new versions available in some other way than just telegram. If not, can you please explain the release model for fdroid?

**Comment by machiav3lli** [comment]
We don't provide test-releases on GH to keep the feedback process direct and avoid spamming the project with issues on GH. We may add a Matrix group in the future, but for now it's what it is.
For now we're doing the last touches on the revamped v0.9.0, so this is why there has been a while since the last public release.
