### ISSUE TITLE
[Feature Request] Display Min and Target SDK in app details

### ISSUE THREAD

**Issue by momobobe** [NeoApplications/Neo-Store#222]
I found the update file for F-Droid repo contains such strings but the official client doesn't display it, so as other unofficial clients. Please add the feature to display such info so users can know that without downloading the actual apps.

**Comment by machiav3lli** [comment]
Users can't download incompatible apps (except if they explicitly chose to, and then it'll fail to install). Otherwise I guess there's surely a fan (group) for each piece of information about apps and it doesn't make sense to overwhelm users with much bloat. Nevertheless, maybe in the future we'll add an option to personalize the shown information.

**Comment by rusty-snake** [comment]
minSDK is displayed now.

As a future step these "info boxes" could be extended (targetSDK, ...) and made configurable (I.e. order, ...).
