### ISSUE TITLE
Permute "new apps" and "recently updated" ?

### ISSUE THREAD

**Issue by jpggithub** [NeoApplications/Neo-Store#274]
The new apps have sometimes some weird names so a description are essential to see if they are interesting for us.
With the actual UI, we must to click on each new app to see what they do. It's not very convenient.

The recently updated apps are... not new apps😉 So their description are less needed than for new apps.

Therefore I suggest to permute the UI between the "new apps" and the "recently updated apps".

Concretely, the recently updated apps could be without description in the top of the screen and the new apps at the "bottom" with a short description.

**Comment by AlterDepp** [comment]
I even cannot read the name of an app if it is longer than 9 characters.

**Comment by machiav3lli** [comment]
@AlterDepp you should be able to in the latest release (two lines max now)

**Comment by machiav3lli** [comment]
I'll consider this in later iterations as the issue would be in having a fitting number of apps in the respective category for the representation form.

**Comment by machiav3lli** [comment]
Solved through the new layout of new apps in 1.0.0

**Comment by AlterDepp** [comment]
The new layout is a little bit better, but the issue is not solved for me. If I set `Number of apps to show in "Recently updated"` to 1 and `Number of apps to show in "New apps"` to 5, I see only two Apps on the _Latest_ screen. For additional new apps, I have to swipe. I am only interested in new apps, not in recently updated apps, so it would be nice to see more than one new app. 
Please reopen the issue.
