### ISSUE TITLE
Manage repo links

### ISSUE THREAD

**Issue by m3thm4th** [NeoApplications/Neo-Store#345]
Clicking on a repository link doesn't bring up Neo Store as an option to open it, but it can be handled by the main F-Droid app.

**Comment by machiav3lli** [comment]
On which version are you?
What link did you tap? And how does it look in the app's settings' "open by default"?

**Comment by m3thm4th** [comment]
I'm on 0.9.8, tap for example this link

https://fdroid.twinhelix.com/fdroid/repo?fingerprint=7B03B0232209B21B10A30A63897D3C6BCA4F58FE29BC3477E8E3D8CF8E304028

and see in the "open by default" only the main F-Droid client and the browsers

**Comment by machiav3lli** [comment]
So, here you go: Fdroid official client still target an old SDK (8 versions late) resulting a huge security flow, at the same time cause it doesn't target A12, it doesn't have restrictions on what intent filters it define.

Further, fdroid already has a specific scheme for repos (fdroidrepo://), which NS supports since the latest version (related issue #200). To support https schemes with a joker host (not defining one), means that NS would be considered a browser, which am not sure is the proper thing to do. But I'll ask the community and see.
