### ISSUE TITLE
Apps vanish from Installed list; tweaking filter selection brings them back

### ISSUE THREAD

**Issue by opusforlife2** [NeoApplications/Neo-Store#357]
Since a few days, an app started vanishing from my Installed apps list. What this means is, when I open Neo Store to the default Installed apps tab, the app doesn't show. But if I search the app in the Explored tab, it shows up. So it's not caused by a filter selection, clearly.

However, if I toggle any filter category and toggle it back, not actually changing anything, the missing app appears in the Installed list again. The cycle repeats every time Neo Store is opened from scratch.

A day or two ago, another app started vanishing in the same way.

This made me realise that the problem seems to have started for each app during one of their update attempts, when either the installer didn't run for some reason, or the download was cancelled and had to be started again. I don't exactly remember.

Edit: sometimes, swiping away from Recents and reopening the app also brings back the full list.

**Comment by dsh2dsh** [comment]
Same here.

**Comment by Offerel** [comment]
Noticed the same since 0.9.13, no idea if it was there before. If you change sorting order in installed app section, all apps are back. But they disappear with next start of Neo Store again.

Hopefully this will be fixed soon.

**Comment by machiav3lli** [comment]
Can you please test 0.9.14-alpha01 provided in the community groups and channel.

**Comment by Offerel** [comment]
I have tried 5,3MB release Apk, but removed first the old version from f-droid. All installed apps are visible, also after restart. 

Currently it try to sync DivestOS repo since more than 7 minutes, hopefully this is only a glitch with the repo itself and not a issue in Neo Store. But I had this before with other apps and the same repo. Just want to let you know that.

Listing in "Explore" tab takes also with this version a huge time. But that's a other issue. The vanishing app issue seems to be fixed for me.

**Comment by machiav3lli** [comment]
Sure it's not #404 (lucky number)?

**Comment by Offerel** [comment]
Maybe. The effect would be the same in my eyes. Restarting the app, solved the notification issue. But as said before, I had the same with Droidify to. it's such a minor that I don't care much.

**Comment by machiav3lli** [comment]
Most possibly was this: `a8a495165288d0d22f9873d0749c2642e98c14e3`
