### ISSUE TITLE
Increasing lag when searching

### ISSUE THREAD

**Issue by awebeer256** [NeoApplications/Neo-Store#368]
The more time I spend searching for things under "explore," the laggier/less responsive the instant search response becomes. In just a few minutes, every keypress is causing the app to freeze for over 30 seconds. Closing the app resets this buildup.

App version: 0.9.10.

**Comment by Generator** [comment]
This is becoming an big issue to search apps.
It's easier to search and install from f-droid.org than using neo-store.

Even on devices with fast CPUs the app lags on search, on low-end/older decices it's just impossible to search.

Instead of instant results let user type then search

**Comment by machiav3lli** [comment]
Can you please report if this got improved in the latest release 0.9.12. Thanks!

**Comment by ASOwnerYT** [comment]
> Can you please report if this got improved in the latest release 0.9.12. Thanks!

I just checked on my Google Pixel 6a running GrapheneOS, and it doesn't seem to have improved. It is still very laggy after searching for a little bit. Hope this helps.

**Comment by awebeer256** [comment]
It's improved, but still present to a degree. I seem to recall there was a discussion somewhere of a proposed change to address this problem and this is exactly what I predicted it would do.

**Comment by S-360** [comment]
The issue is still there for me and makes the app unusable. Version 0.9.12 on Samsung A53

**Comment by machiav3lli** [comment]
As almost no comments are really productive and users reporting it earlier didn't report on progress (excluding @awebeer256 and the users in the community group). I would like to invite the users here to test the lately released 0.9.13-alpha01 in the community group (accessible through Telegram or Matrix) and otherwise provide more extensive description of the issue, as some are mixing slow search results with freezes, crashes or other performance issues (which are as reported in the community group, are mostly gone).

**Comment by awebeer256** [comment]
> Fixed with 0.9.13 for me.

Same here.
