### ISSUE TITLE
Add toggle to disable warnings about known vulnerabilities

### ISSUE THREAD

**Issue by m3thm4th** [NeoApplications/Neo-Store#413]
The app continuously sends notifications about apps containing known vulnerabilities. This scares people whom I install the app to and have no understanding of what it means, and it's nagging anyway for those who understand. So please add a toggle to disable the notifications, the visual warning in the app description is enough for normal people. The toggle should probably be disabled by default for new users, this way clueless users will not be scared away and advanced users will find the toggle by themselves when tinkering with the settings.

**Comment by machiav3lli** [comment]
An option is planned but it won't be disabled by default.

**Comment by xdevs23** [comment]
This is very annoying. I receive about 14 notifications per day about the same app. And when I tap on the notification, it does not tell me what the vulnerability is and what CVSS score it has. Hence the usefulness of this feature is limited to knowing that there is some vulnerability in a specific app. This just makes me worry about it even if it might not even be critical enough to be worried about. 

I'd rather suggest adding some kind of risk acceptance feature where I can toggle "Ignore notifications for this version" for the affected app until it is updated.

The affected app might not get a fix quickly and thus users will be annoyed many times every day as if it was the most important thing. Don't get me wrong: there are important notifications and some vulnerabilities have to be taken care of immediately. But the app does not even tell me the severity of it and if the severity is low, it's just a constant annoyance.

Disabling the notifications in the system settings is not a solution since it also disables notifications for all other apps.
