### ISSUE TITLE
Don't force disabling battery optimization

### ISSUE THREAD

**Issue by unbranched** [NeoApplications/Neo-Store#440]
From v. 0.9.15 a message forces the user to disable battery optimization for the app, not giving an option to skip or ignore.
That's a bad practice, let the user choose.

**Comment by machiav3lli** [comment]
We already had the discussion in the community group and I'll consider adding an option for your use cases

**Comment by jeremiah-miller** [comment]
I primarily use droidify as my app store, but I like to keep an eye on alternatives. Trying to go check out the latest update and not being able to get past that screen makes me want to uninstall the app, and i'd bet the same will happen for other people who download it to try out and see what the deal is before committing to it as their main store app

**Comment by mozhin** [comment]
So can we expect an ability to disable this "feature" or do I look for an alternative?

**Comment by Magneticdud** [comment]
Sorry but I don't like stuff to be forced down my throat. I prefer crashes (?) than being forced to have something in background that i don't need, no matter how much optimized it is, even if it takes 4 mb of RAM. My app is set to check updates every 99999 hours. I only want to check updates manually, even the play store is set like that. I just uninstall this update and go back to droidify

**Comment by machiav3lli** [comment]
@Magneticdud noone is forcing anything on you. The project is FOSS, you can fork and remove what you don't like.

No community needs such attitude...

**Comment by Magneticdud** [comment]
I wrote down my opinion very rudely but how you can say nobody is forcing me? The dialog is designed to be "disable battery optimization or uninstall this app". The user is literally forced, no other way.

Sure, it's trivial to fix for me, just go to line 55 on https://github.com/NeoApplications/Neo-Store/blob/master/src/main/kotlin/com/machiav3lli/fdroid/ui/pages/PermissionsPage.kt and make it work with the opposite logic, but it's also easier to install droidify 

It might be a translation issue because English is not my native language, but you wrote "i will consider to add an option" and not "it's planned to be made optional in a future release in the next months"; in that sentence i read a "i still think that it must be forced, i don't really want to add such option for just 4 ungrateful users".

**Comment by Sir-Photch** [comment]
Yes, definetly not cool. I had no problems or any crashes with battery optimization disabled.

**Comment by machiav3lli** [comment]
@Magneticdud It's definitely a translation issue. If you were involved in any discussions before in projects, where am involved in, on making things optional you'd know that I take always giving options over forcing things. That said, the "months" is mainly related to the fact that I'm not having much time to invest in this, but you may be sure that an option will come. The only question is when… my answer: no ETA.

And then again, no one is forcing anything on you, it's a FOSS, you can fork and maintain your own variant (for short or long term) or maybe contribute to better discussion culture with a solution idea or even then a following PR.

**Comment by Magneticdud** [comment]
no no, i'm perfectly fine in waiting months, i was saying "please do this eventually", and as i said, i had the impression, when translated in my language, that it won't be fixed, ever

my coding skills are too poor to provide a solution, except bypass the whole system, unfortunately

**Comment by rusty-snake** [comment]
I don't want to put pressure on it, but I would welcome a release with this fix.

**Comment by xdevs23** [comment]
It went away for a while but now it came back and I can't get it to disappear.

![Screenshot_20230503-111625](https://user-images.githubusercontent.com/6959245/235878188-4d1748f6-040e-461a-bfcb-44865e048f7c.png)

**Comment by xdevs23** [comment]
I never had an issue with battery optimization enabled, except that this message keeps popping up when I launch Neo Store.

**Comment by Decimation** [comment]
I'm encountering the same issue. I was able to put up with it temporarily by turning off battery optimization when I actually use the app, then re-enabling it. However, I eventually just uninstalled and switched back to alternative apps. It's been half a year since this issue was opened, and no updates? I don't mean to sound rude or pushy, but it's a minor change.

**Comment by rusty-snake** [comment]
My workaround it to permanently have one app installed that I do not updated, because from the update notification you can use the app. Anyway 5 month without a bugfix release are annoying, I agree.

**Comment by Magneticdud** [comment]
I see in the code has been already patched to ignore this, but the release is waiting the 1.0 with many changes and improvements, so we need to be more patience :) If you compile the app by yourself, it does not have this problem

(l'm not a dev, i am an user, last time i compiled this app was some months ago)

**Comment by rusty-snake** [comment]
> but the release is waiting the 1.0 with many changes and improvements, so we need to be more patience

And that's the problem. You can cherry-pick without conflict so a 0.9.16 release with some bugfixes before the big 1.0 release (which is in alpha for 4 month now) should not be that difficult.

(Repeating, not against any dev, they do a great work on this app)
