### ISSUE TITLE
Add short descriptions to app info sites or improve display of them on the app list

### ISSUE THREAD

**Issue by Retardium** [NeoApplications/Neo-Store#470]
At the moment, the short descriptions in the app list are only partially displayed - even if you press on an entry for a longer time and thus expand the extended quick options for the entry.
Short descriptions are also not displayed on the info page of the respective app.
![ResizedImage20230509_042026](https://user-images.githubusercontent.com/32235655/236978251-37429ca4-5fb0-48cf-ab07-b811800e4fe0.png)

This is only a minor issue, but it could probably be easily solved by simply displaying the complete short description at the top of the info page.
![ResizedImage20230509_042434](https://user-images.githubusercontent.com/32235655/236978683-990d7ccc-2058-47ec-b3b0-11296a8798f7.png)

Otherwise, you could certainly do it in such a way that the full description is displayed in the app list as soon as you press and hold on the respective entry.

**Comment by machiav3lli** [comment]
Here's my point on the thing:
- short description of most apps is another formulation of the first one or two sentences of the full description, that's why it's not present in the app sheet.
- in my local code base the thing with having more than one line of short description in the card is already solved, but maybe I'll consider differentiating between expanded card and not.

**Comment by machiav3lli** [comment]
Should be fixed with latest alpha (available through the community groups and TG channel for test)
