### ISSUE TITLE
NavBar covers whole screen in 1.0.0-alpha06

### ISSUE THREAD

**Issue by Wojtaz0w** [NeoApplications/Neo-Store#507]
I can't even enter settings to disable it! 

![Screenshot_20230821-182606_Neo Store-beta.png](https://github.com/NeoApplications/Neo-Store/assets/104674625/4af64b35-a0a0-4e54-92f0-9e63bae51217)

**Comment by machiav3lli** [comment]
Test build bugs are exclusively discussed in the groups! They're distributed and discussed only there to avoid such mess here! The issue is already known and will be solved by next test build (If you have root, you may fix it in: /data/data/com.machiav3lli.fdroid/shared_prefs/com.machiav3lli.fdroid_preferences.xml by changing alt_navbar_item's value to false).
